### ISSUE TITLE
SIONlib

### ISSUE THREAD

**Issue by andreas-schreiber** [pencil-code/pencil-code#3]
Hi all, did ever someone had a look on SIONlib?
http://www.fz-juelich.de/ias/jsc/EN/Expertise/Support/Software/SIONlib/_node.html

**Comment by PABourdin** [comment]
I heard of it and checked it long time ago. If you like you can clone one of the IO-modules and try to implement a "io_sion.f90"... But I don't see an immediate effect, because still the particle modules are not using the IO-modules, so the benefits for the Pencil Code are little (in its current state).
