### ISSUE TITLE
Python pencil module does not import

### ISSUE THREAD

**Issue by beresnyak** [pencil-code/pencil-code#7]
# Down below is the error message (I did run sourceme.csh beforehand)

Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2

> > > import pencil
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/u/beres/pencil/pencil-code/python/pencil/**init**.py", line 15, in <module>
> > >     from pencil.files.xyaver import *
> > >   File "/u/beres/pencil/pencil-code/python/pencil/files/xyaver.py", line 12, in <module>
> > >     from subprocess import check_output
> > > # ImportError: cannot import name check_output
> > > 
> > > There's no subprocess.py in the codebase.
> > > Also "subprocess" is not defined anywhere in *.py files
> > > the only matches are in
> > > ./python/pencil/files/xyaver.py
> > > ./python/pencil/files/yzaver.py
> > > ./bin/test/test_git-pc.py

**Comment by alexrichert** [comment]
I've seen something like this before, it's an issue with the Python 
installation and not having the right modules... If nothing else, try 
using something like Anaconda or Enthought Python installations. If 
you're on a system that uses the "modules" system, make sure to load a 
complete Python install, e.g., "modules load python/2.7" or similar.
Alex

On 30.04.2016 21:10, Andrey Beresnyak wrote:

>   Down below is the error message (I did run sourceme.csh beforehand)
> 
> Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
> 
> ```
>         import pencil
>         Traceback (most recent call last):
>         File "", line 1, in
>         File
>         "/u/beres/pencil/pencil-code/python/pencil/*init*.py",
>         line 15, in
>         from pencil.files.xyaver import *
>         File
>         "/u/beres/pencil/pencil-code/python/pencil/files/xyaver.py",
>         line 12, in
>         from subprocess import check_output
> 
> 
>           ImportError: cannot import name check_output
> 
>         There's no subprocess.py in the codebase.
>         Also "subprocess" is not defined anywhere in *.py files
>         the only matches are in
>         ./python/pencil/files/xyaver.py
>         ./python/pencil/files/yzaver.py
>         ./bin/test/test_git-pc.py
> ```
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/pencil-code/pencil-code/issues/7

## 

Alexander J.W. Richert
Exoplanets and Stellar Astrophysics Laboratory (667), NASA GSFC
Dept. of Astronomy & Astrophysics, Penn State University
525 Davey Lab, University Park, PA 16802
(301) 286-6816
ajr327@psu.edu
http://www.alexrichert.com/

**Comment by alexrichert** [comment]
To clarify, "subprocess" is a general Python module, not a Pencil module.

**Comment by fredgent** [comment]
Hi Andrey,

The module subprocess is not a pencil-code, but part of the python 
environment. I have had this message a few times on the CSC cluster and 
it is typically because I have forgotten to load the appropriate python 
module. It is part of the python 2.7 and later distribution.

If it is your own machine it should be standard with linux, not sure 
about windows/mac. I often find I need to source sourceme.sh with a new 
session, before the pencil python is found by the python path, so I 
added these line to my .bashrc file in my home directory

export PENCIL_HOME
export 
PATH=+$PATH:${PENCIL_HOME}/bin:+${PENCIL_HOME}/utils:+${PENCIL_HOME}/axel
if [ -z $PYTHONPATH ]; then
    PYTHONPATH="$PENCIL_HOME/python:$PWD/python"
else
    PYTHONPATH="$PYTHONPATH:$PENCIL_HOME/python:$PWD/python"
fi
export PYTHONPATH
export PYTHONSTARTUP=$HOME/.pythonstart

with the file .pythonstart containing the following lines (useful to 
load commonly used modules and history)

# startup script for python to enable saving of interpreter history and

# enabling name completion

# import needed modules

import atexit
import os
import readline
import rlcompleter
import numpy as np
import matplotlib.pyplot as plt
import pencil as pc

# where is history saved

historyPath = os.path.expanduser("~/.pyhistory")

# handler for saving history

def save_history(historyPath=historyPath):
     import readline
     readline.write_history_file(historyPath)

# read history, if it exists

if os.path.exists(historyPath):
     readline.set_history_length(10000)
     readline.read_history_file(historyPath)

# register saving handler

atexit.register(save_history)

# enable completion

readline.parse_and_bind('tab: complete')

# cleanup

del os, atexit, readline, rlcompleter, save_history, historyPath

Regards,

Fred

**Comment by beresnyak** [comment]
Hi, Fred

Thanks for this clarification. Indeed, older Python 2.6.6 was the culprit,
2.7 works just fine.

Thanks,
  Andrey
